# Configuración para Ambiente de Desarrollo (Dev) - SRI Pruebas
sri.environment=1
sri.sandbox-mode=true
sri.recepcion-url=https://celcer.sri.gob.ec/comprobantes-electronicos-ws/RecepcionComprobantesOffline
sri.autorizacion-url=https://celcer.sri.gob.ec/comprobantes-electronicos-ws/AutorizacionComprobantesOffline
sri.anulacion-url=https://celcer.sri.gob.ec/comprobantes-electronicos-ws/AnulacionComprobantesOffline

logging.level.com.factura.demo=DEBUG
