# Configuración para Ambiente de Producción (Prod) - SRI Producción
sri.environment=2
sri.sandbox-mode=false
sri.recepcion-url=https://cel.sri.gob.ec/comprobantes-electronicos-ws/RecepcionComprobantesOffline
sri.autorizacion-url=https://cel.sri.gob.ec/comprobantes-electronicos-ws/AutorizacionComprobantesOffline
sri.anulacion-url=https://cel.sri.gob.ec/comprobantes-electronicos-ws/AnulacionComprobantesOffline

logging.level.com.factura.demo=INFO
