spring.application.name=demo
spring.profiles.active=dev
server.port=${PORT:8080}

# R2 Storage Configuration
r2.bucket-name=${R2_BUCKET_NAME:hipposalud}
r2.access-key=${R2_ACCESS_KEY:691e6541fd892b8f99909afbb21a5d0a}
r2.secret-key=${R2_SECRET_KEY:d5b32abf691a5ae209d1de1b3234ca94b2b911285d63c543c596de522f688b3e}
r2.endpoint=${R2_ENDPOINT:https://6a9707e1eb7a0b7a5569b88e9a9bac7a.r2.cloudflarestorage.com}
r2.cdn-url=${R2_CDN_URL:https://pub-a4aa4df510a34131923212e56ad459ae.r2.dev}
